name: syntaxify
description: The Flutter UI Compiler. Define once, compile to any design system. , Build Your Next Flutter App Designs in Minutes, And Toggle Design Systems in Seconds.
version: 0.2.0-beta
repository: https://github.com/ihardk/syntaxify
issue_tracker: https://github.com/ihardk/syntaxify/issues
homepage: https://github.com/ihardk/syntaxify

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # CLI
  args: ^2.4.0
  mason_logger: ^0.3.3

  # Parsing
  analyzer: ^7.5.9

  # Code Generation
  code_builder: ^4.10.0
  dart_style: ^3.1.1

  # Data Models
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.0

  # File System
  path: ^1.9.0
  file: ^7.0.0

  # Caching
  crypto: ^3.0.3

  # Linting
  custom_lint_builder: ^0.8.0

  # File Watching
  watcher: ^1.1.0
  yaml: ^3.1.3

dev_dependencies:
  # Build
  build_runner: ^2.4.0
  freezed: ^3.2.3
  json_serializable: ^6.7.0
  
  # Testing
  test: ^1.24.0
  mocktail: ^1.0.0
  lints: ^6.0.0

executables:
  syntaxify: syntaxify
