name: syntax
description: AST-based Flutter UI code generator with multi-style design system support
version: 0.0.3

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  # CLI
  args: ^2.4.0
  mason_logger: ^0.2.0
  
  # Parsing
  analyzer: ^6.4.0
  
  # Code Generation
  code_builder: ^4.10.0
  dart_style: ^2.3.0
  
  # Data Models
  freezed_annotation: ^2.4.0
  json_annotation: ^4.8.0
  
  # File System
  path: ^1.9.0
  file: ^7.0.0

dev_dependencies:
  # Build
  build_runner: ^2.4.0
  freezed: ^2.4.0
  json_serializable: ^6.7.0
  
  # Testing
  test: ^1.24.0
  mocktail: ^1.0.0
  lints: ^3.0.0

executables:
  syntax: syntax
